gha: update workflows

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -21,93 +21,74 @@ on:
 #    # run every night at midnight
 #    - cron:  '0 0 * * *'
 
-jobs:
-  # Special job which automatically cancels old runs for the same branch, prevents runs for the
-  # same file set which has already passed, etc.
-  pre_job:
-    name: Skip Duplicate Jobs Pre Job
-    runs-on: ubuntu-latest
-    outputs:
-      should_skip: ${{ steps.skip_check.outputs.should_skip }}
-    steps:
-      - id: skip_check
-        uses: fkirc/skip-duplicate-actions@4c656bbdb6906310fa6213604828008bc28fe55d # v3.3.0
-        with:
-          cancel_others: 'true'
-          github_token: ${{ github.token }}
+env:
+  COLUMNS: '120'
 
+jobs:
   # Lint checks which don't depend on any service containers, etc. to be running.
   lint-checks:
-    needs: pre_job
-    # NOTE: We always want to run job on master since we run some additional checks there (code
-    # coverage, etc)
-    if: ${{ needs.pre_job.outputs.should_skip != 'true' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
-    name: '${{ matrix.name }} - Python ${{ matrix.python-version-short }}'
+    name: 'Lint - Python ${{ matrix.python-version-short }}'
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        include:
-          - name: 'Lint Checks (pants runs: bandit, black, docformatter, isort, flake8, shfmt, shellcheck, hadolint)'
-            python-version-short: '3.8'
-            python-version: '3.8.10'
-
-    env:
-      COLUMNS: '120'
+        # NOTE: We need to use full Python version as part of Python deps cache key otherwise
+        # setup virtualenv step will fail.
+        python:
+          - {version-short: '3.11', version: '3.11.11'}
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
-      - name: 'Set up Python for Pants (3.9)'
-        uses: actions/setup-python@v2
+      - name: 'Set up Python (${{ matrix.python.version }})'
+        id: python
+        uses: actions/setup-python@v5
         with:
-          python-version: '3.9'
-      - name: 'Set up Python (${{ matrix.python-version }})'
-        uses: actions/setup-python@v2
+          python-version: '${{ matrix.python.version }}'
+
+      - name: Initialize Pants and its GHA caches
+        uses: ./.github/actions/init-pants
         with:
-          python-version: '${{ matrix.python-version }}'
-
-      - name: Get Pants Cache Merge Base Commit (base branch commit to pull cache from)
-        id: pants-cache-commit
-        run: |
-          COMMIT=$(git merge-base ${GITHUB_BASE_REF:-main} HEAD | head -n1)
-          echo MERGEBASE=${COMMIT}
-          echo "::set-output name=MERGEBASE::${COMMIT}"
-
-      - name: Cache Pants Caches
-        uses: actions/cache@v2
-        id: pants-cache
-        with:
-          path: |
-            ~/.cache/pants/setup
-            ~/.cache/pants/lmdb_store
-            ~/.cache/pants/named_caches
-          key: ${{ runner.os }}-pants-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-pants-${{ steps.pants-cache-commit.outputs.MERGEBASE }}
-            ${{ runner.os }}-pants-
-
-      - name: Cache Python Dependencies
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('build-support/lockfiles/*', 'poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-${{ matrix.python-version }}-
-
-      - name: Bootstrap Pants
-        run: |
-          ./pants --version
+          # To ignore a bad cache, bump the cache* integer.
+          gha-cache-key: cache0-py${{ matrix.python.version }}
 
       - name: Lint
         run: |
           ./pants lint ::
 
       - name: Upload pants log
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
-          name: pants-log
+          name: pants-log-py${{ matrix.python.version }}-lint
           path: .pants.d/pants.log
         if: always()  # We want the log even on failures.
+
+  set_merge_ok:
+    name: Set Merge OK (Lint)
+    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
+    needs:
+      - lint-checks
+    outputs:
+      merge_ok: ${{ steps.set_merge_ok.outputs.merge_ok }}
+    runs-on: ubuntu-latest
+    steps:
+      - id: set_merge_ok
+        run: echo 'merge_ok=true' >> ${GITHUB_OUTPUT}
+
+  merge_ok:
+    name: Merge OK (Lint)
+    if: always()
+    needs:
+      - set_merge_ok
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          merge_ok="${{ needs.set_merge_ok.outputs.merge_ok }}"
+          if [[ "${merge_ok}" == "true" ]]; then
+            echo "Merge OK"
+            exit 0
+          else
+            echo "Merge NOT OK"
+            exit 1
+          fi
